xcodeproj: Shared.xcodeproj
scheme: Shared-Debug
source_directory: Shared
output_directory: Slather/Output
ignore:
  - Shared/ErrorHandling/AssertionHandler.swift
  - Shared/Extensions/MapKit/*
  - Shared/Extensions/UIKit/*
  - Shared/PlaceLookup/*
  - Shared/Sourcery/*
  - Shared/UI/*
  - SharedIntegrationTests/*
  - SharedTestComponents/*
  - SharedTests/*
